apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: front-end-hpa
  namespace: application
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: front-end
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 1 # normally at 70-80